### ISSUE TITLE
gasの処理作成

### ISSUE THREAD

**Issue by tkeng01** [tkeng01/keiba-baba#5]
スプレッドシートの値を配列に格納する処理を作成する。

**Comment by ry0-cha-ng** [comment]
GASを用いて実現したい内容は下記2点
（A）マスターとなるcsvファイルから必要な情報を抽出して、新たにスプレッドシートを作成
（B）新たに作成したスプレッドシートをjson形式で出力

tkのJSON読み取り機構検証を進めるため、タスク優先度は（B）→（A）とする。

**Comment by ry0-cha-ng** [comment]
>tkのJSON読み取り検証を進めるため、タスク優先度は（B）→（A）とする。

**Comment by ry0-cha-ng** [comment]
>（1）新しいスプレッドシート（ss）を作成  
完了。
「scripts」→「csv to ss」→「ss_create.gs」を実行し、スプレッドシート「test2」の作成に成功した。  

■次タスク
（2）csvファイルからデータを抽出し、ssへ書き込み

**Comment by tkeng01** [comment]
@ry0-cha-ng 
niceです。
業務終わったので確認してみます。

**Comment by tkeng01** [comment]
gas等も形跡として、githubにpushしてみてはどうでしょうか。

**Comment by ry0-cha-ng** [comment]
GoogleAppScriptと

**Comment by ry0-cha-ng** [comment]
claspの導入が完了、GoogleAppScriptのスクリプトファイルをGithubで管理する方法を確立した。

**Comment by ry0-cha-ng** [comment]
進捗状況の整理  

■実現したいこと  
（A）マスターとなるcsvファイルから必要な情報を抽出して、新たにスプレッドシートを作成  
（B）新たに作成したスプレッドシートをjson形式で出力  

■進捗  
（A）マスターとなるcsvファイルから必要な情報を抽出して、新たにスプレッドシートを作成  
→対応中（進捗50％）。  

（1）新しいスプレッドシート（ss）を作成  
→完了。「ss_create」スクリプト実行により新規ssの作成に成功した。  

（2）csvファイルからデータを抽出し、ssへ書き込み  
→現在対応中。「csv_to_ss」スクリプト実行により、データソース用csvから各レースの確定順位1～3着馬情報を抽出し、（A）で作成したssに記載できれば完了。  

（B）新たに作成したスプレッドシートをjson形式で出力  
→完了した。  
「ss_to_json」スクリプト実行により以下のようにjson形式で出力できた。  
https://script.googleusercontent.com/macros/echo?user_content_key=MJkULjg3KTI7I77n3MYWf5AmlFV86dfypCdNwVi0U69V-8tv7G9WZQAmMA5dERwo2I6FYgDgXxdxpEvk9CNgPPgVh7mzHw4im5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnETknLM4GDiOHpV0aqgYiPvt6ZT54maqn9wyjgVu0OAxBX6miNEJU_8mEbRVLeFBbA&lib=MN3iBNGn_o1ZGBeLWCbV_vEUJgFJUyX3F  

実際に運用する際はスクリプト内の下記変数を書き換えることで対応可能。  
・ssID（データソースとなるssのID）  
・ssSheetName（ssの対象シート名）  

■残件  
・「csv_to_ss」作成  
・（2）テスト

**Comment by ry0-cha-ng** [comment]
下記残件が完了したのでクローズ。  
・「csv_to_ss」作成  
・（2）テスト  

**「csv_to_ss」の主な挙動**  
・csv展開用ssを新規作成する  
・Googleドライブ「csv」フォルダ内で最後に更新されたファイルを特定する  
・最後に更新されたcsvファイル内のデータをssに展開する(全データ)  
・ss内に「top3」シートを作成し、1～3着馬のみのデータを抽出、記載する  
・「top3」シートにヘッダーを追加する  

**「ss_to_json」の主な挙動**
・Googleドライブ「ss_from_csv」フォルダ内で最後に更新されたファイルを特定する  
・対象ファイルのデータをjson形式で出力する

**Comment by ry0-cha-ng** [comment]
### **具体的な利用方法**###

1. TARGET flontier JVから必要なデータをcsv形式でGoogleドライブ上「csv」フォルダに出力する  
2. 「csv_to_ss」を実行し、ss形式に変換する。
https://script.google.com/macros/s/AKfycbyDgV3OhpVwbJGiWkSj4B7i2fuFucXXrjYSOgoq36ctOwlAShc/exec  
3. 「ss_to_json」を実行し、ssのデータをjson形式で出力する
https://script.google.com/macros/s/AKfycbwDZSXsZRDzV3-R5_XavC37-LEAohi2tz0Ok48NHtW_R1j6fxtG/exec

**Comment by tkeng01** [comment]
https://script.google.com/macros/s/AKfycbwDZSXsZRDzV3-R5_XavC37-LEAohi2tz0Ok48NHtW_R1j6fxtG/exec
