### ISSUE TITLE
データLABから結果データをDL

### ISSUE THREAD

**Issue by tkeng01** [tkeng01/keiba-baba#6]
データCSVをスプレッドシートへ適用する。

**Comment by tkeng01** [comment]
以下の情報をCSVファイルとして書き出し確認
年 | 月 | 日 | 場所 | レース番号 | 略レース名 | 芝ダ | 距離 | 天候 | 馬場状態 | 馬名 | 確定着順 | 着差タイム | 人気 | 走破タイム（秒） | 通過順1角 | 通過順2角 | 通過順3角 | 通過順4角 | 上がり3Fタイム

**Comment by ry0-cha-ng** [comment]
csvファイルをTARGET frontier JVから直接Googleドライブの「csv」フォルダ直下に
配置できるよう調整した。  

参考：TARGETのファイルをGoogleドライブで共有  
https://ittai.net/2016/01/target%E3%81%AE%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92google%E3%83%89%E3%83%A9%E3%82%A4%E3%83%96%E3%81%A7%E5%85%B1%E6%9C%89/

**Comment by ry0-cha-ng** [comment]
＜メモ＞
■GoogleSheetsの仕様
--
セル数：500万セル（シート合計）
行数：無制限
 
■1年間の各レース1～3着馬のデータ数
年間約3400R×3（1～3着馬）＝12,000
 
■馬場計算システムで使ってる項目数（列数）
20（A～T列）
 
■1スプレッドシートに詰められるデータ数（行数）
5,000,000 / 20 = 250,000
 
■1スプレッドシートに詰められるデータの年数
250,000 / 12,000 = 20.833... ≓ 20

**Comment by ry0-cha-ng** [comment]
とりあえず内容が変動しない2010年～2019年の  
10年分のデータを「csv」フォルダに出力した。  
TARGET frontier JVからの出力に約15分を要した。
